trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  configuration: release
  targetFramework: netcoreapp3.1

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: -c $(configuration) -f $(targetFramework)

    - task: DotNetCoreCLI@2
      displayName: test
      inputs:
        command: test
        projects: '**/*.Tests.csproj'
        publishTestResults: false

    - task: DotNetCoreCLI@2
      displayName: publish
      inputs:
        command: publish
        arguments: -c $(configuration) -o app/publish -f $(targetFramework)
        zipAfterPublish: false